### ISSUE TITLE
cv template footer - possible typo

### ISSUE THREAD

**Issue by waternumbers** [svmiller/stevetemplates#2]
**Issue**

I've had trouble getting the footer to generate correctly with the CV template - the <author>-<title> part was replaced by the page number.

**Possible Fix**

Lines 202-203 read
`
\lfoot{
`
`
\cfoot{\scriptsize  $author-meta$ - $title$ }}
`
when replaced with
`
\lfoot{}
`
`
\cfoot{\scriptsize  $author-meta$ - $title$ }
`
footer generates correctly

**Comment by svmiller** [comment]
Huh. I see it now. It's weird because I'd never know there was an issue from my end. I'll fix that now. Thank you for bringing that to my attention.

**Comment by svmiller** [comment]
Should've staged that commit now (with time to spare before the grad class starts). I'll close it after the class if there's no other issue.

**Comment by svmiller** [comment]
Calling this closed. I think we're good here.

**Comment by waternumbers** [comment]
Cheers that fixed the problem for me - only just had time to test
